version: "3"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.11.2"
        PHOENIX_VERSION: "1.5.7"
        INSTALL_NODE: "true"
        NODE_VERSION: "10"

    volumes:
      - ..:/workspace:cached
    ports: 
      - 4000:4000
    command: sleep infinity
    networks: 
      - music_map

  db:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - music_map
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_map_dev

  tileserver:
    image: maptiler/tileserver-gl
    volumes:
      - ./map_tiles:/data
    networks: 
      - music_map
    ports:
      - 8181:80
  
  nominatim:
    image: peterevans/nominatim:latest
    networks: 
      - music_map
    environment:
      NOMINATIM_PBF_URL: http://download.geofabrik.de/north-america/us/louisiana-latest.osm.pbf
    ports:
      - 8080:8080
    volumes:
      - nominatim-data:/srv/nominatim/data
    entrypoint: /docker-entrypoint.sh
  
volumes:
  postgres-data:
  nominatim-data:

networks:
  music_map:
      driver: bridge