version: "3"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.11.2"
        PHOENIX_VERSION: "1.5.7"
        INSTALL_NODE: "true"
        NODE_VERSION: "10"

    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_map_dev

volumes:
  postgres-data:
    name: music_map_postgres
